export const menuItems = [
  {
    id: "home-section",
    type: "main",
    label: "HOME - DASHBOARD",
    tipKey: null,
    upercase: true,
    disabledItem: false,
    url: "/home",
    icon: "home",
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "search-section",
    type: "main",
    label: "PESQUISAR",
    tipKey: "( Ctrl+P )",
    upercase: true,
    disabledItem: false,
    url: null,
    icon: "search",
    classStyle: "",
    goToUrl: () => {}
  },
  {
    id: "budget-section",
    type: "main",
    label: "ORÇAMENTOS",
    tipKey: null,
    upercase: true,
    disabledItem: true,
    url: null,
    icon: "list-alt",
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "new-budget",
    type: "sub",
    label: "Novo Orçamento",
    tipKey: "( Ctrl+N )",
    upercase: false,
    disabledItem: false,
    url: null,
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "budget-await",
    type: "sub",
    label: "Aguardando",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: "/budget?type=await",
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "budget-success",
    type: "sub",
    label: "Aprovados",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: "/budget?type=success",
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "budget-canceled",
    type: "sub",
    label: "Cancelados",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: "/budget?type=canceled",
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "budget-reapproved",
    type: "sub",
    label: "Reprovados",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: "/budget?type=reapproved",
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "budget-expired",
    type: "sub",
    label: "Expirados",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: "/budget?type=expired",
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "admin-section",
    type: "main",
    label: "Administração",
    tipKey: null,
    upercase: true,
    disabledItem: true,
    url: null,
    icon: "tasks",
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "admin-profile",
    type: "sub",
    label: "Meu Perfil",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: null,
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "admin-customers",
    type: "sub",
    label: "Clientes",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: "/customers",
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "admin-products",
    type: "sub",
    label: "Produtos",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: "/products",
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "admin-users",
    type: "sub",
    label: "Usuários",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: "/users",
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "admin-system",
    type: "sub",
    label: "Configurações",
    tipKey: null,
    upercase: false,
    disabledItem: false,
    url: null,
    icon: null,
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "app-lock",
    type: "main",
    label: "Bloquear Tela",
    tipKey: "( Ctrl+L )",
    upercase: true,
    disabledItem: false,
    url: null,
    icon: "lock",
    classStyle: "",
    goToUrl: (func: Function) => func
  },
  {
    id: "app-logout",
    type: "main",
    label: "Logout - Sair",
    tipKey: null,
    upercase: true,
    disabledItem: false,
    url: null,
    icon: "exit",
    classStyle: "",
    goToUrl: (func: Function) => func
  },
];
